### ISSUE TITLE
[UX Improvement] Setup page 

### ISSUE THREAD

**Issue by RabebOthmani** [interledger/web-monetization-extension#564] opened 2024-09-02 15:32 UTC
### Steps to reproduce

**_This is based on testers feedback_**
It can be confusing to understand the steps to take to configure the extension , that is to successfully connect it to a wallet and setup a budget to use. There's room to make the experience on this page better and easier for the users. 
For example: public key might be confusing for non technical users / the connect button is always enabled 

### Expected result

- Connect button should be disabled until all steps are taken. This is a visual cue for the user that something needs to be done. 

- Review and update copy to be clearer 

- Update grey out colour to indicate that a field needs filling  

### Actual result

current page 

### Operating system

Windows

### Browsers

Chrome

### Extension version

beta

**Comment by sidvishnoi** [comment] 2024-09-03 12:59
Duplicate of https://github.com/interledger/web-monetization-extension/issues/565

**Closed by sidvishnoi** 2024-09-03 12:59 UTC
Labels: triage, area: popup, UX improvements
